### ISSUE TITLE
will this paginate / have a scroll body?

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/trendyQC#52]
will this table just endlessly grow with saved filters or will it be a fixed height scroll? doesn't look to be using dataTables

![image](https://github.com/eastgenomics/trendyQC/assets/45037268/1a543712-cc84-4968-ae1e-0a410ec2ea62)

**Comment by Yu-jinKim** [comment]
It will paginate: https://github.com/eastgenomics/trendyQC/blob/local_dev/trendyqc/trend_monitoring/views.py#L144
